export const ACTION_TYPES = {
  SET_SIZE: 'SET_SIZE',
  SET_GAMEOVER: 'SET_GAMEOVER',
  TOGGLE_CURRENT_PLAYER: 'TOGGLE_CURRENT_PLAYER',
  SET_ORIGIN: 'SET_ORIGIN',
  SET_CAN_CONNECT_WITH: 'SET_CAN_CONNECT_WITH',
  SET_USED_FENCES: 'SET_USED_FENCES',
  SET_FENCED_BY_P1: 'SET_FENCED_BY_P1',
  SET_FENCED_BY_P2: 'SET_FENCED_BY_P2',
  RESET_MOVES: 'RESET_MOVES',
}